### ISSUE TITLE
Removed classes briefly reappear on dashboard when navigating through site

### ISSUE THREAD

**Issue by 10drck** [ChuckVisuals/UMD-Course-Checker#9]
When a class is removed from the dashboard, it initially disappears as expected. However, navigating to different routes and then back to the dashboard causes the removed class to briefly reappear before disappearing again.

![bug-gif](https://github.com/ChuckVisuals/UMD-Course-Checker/assets/93065586/10d3529e-f82f-4d3f-a80d-b7a2cf9dcead)

**Comment by ChuckVisuals** [comment]
Fixed in d320841
